### PR TITLE
Branch errortrapping

### PR DESCRIPTION
**Pull request by AlanPBourke**
The ON ERROR approach in ExpandMacros is difficult to use in a scenario where there is an uplevel form Error() event in play. I have converted it to TRY...CATCH.

### CODE REVIEW

**Comment by vespina** [comment]
The reason behind using ON ERROR instead of TRY CATCH is to keep compatibility with older versions of VFP. So, despite de obvious advantages of using TRY CATCH in this particular scenario, I think backward compatibility should be maintained.

That said, I see your point regarding the problem with Error events. So, I would recommend to use compiler directives to use TRY CATCH or ON ERROR depending on the current VFP version.

**Comment by vespina** [comment]
FYI, I just uploaded a new version including your suggestion about using TRY-CATCH when is possible.  Thanks again for using this library and pointing this out.

**Comment by AlanPBourke** [comment]
Thanks for developing it !

-- 
  Alan Bourke
  alanpbourke (at) fastmail (dot) fm

**Comment by AlanPBourke** [comment]
Victor

I'm having an issue on site with this. The job goes into the queue but the printer doesn't print. If I create an .out file and send it with the rawprint command line utility it prints. Any quick pointers? Thanks.

-- 
  Alan Bourke
  alanpbourke (at) fastmail (dot) fm

**Pull request closed without merging**
